name: docker

on:
  branches:
    - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker
        run: |
          docker build -t docker.pkg.github.com/skaji/docker-playground/image:latest .
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login docker.pkg.github.com -u skaji --password-stdin
          docker push docker.pkg.github.com/skaji/docker-playground/image:latest
